name: "Build Release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "datestamp=$(date +'%s')" >> $GITHUB_ENV

      - name: Versioning
        run: |
          echo -e "\n# Information added by Github Action packaging script on ${{ env.date }}" >> topographia.info.yml
          echo "version: '${{ github.ref_name }}'" >> topographia.info.yml
          echo "project: 'topographia'" >> topographia.info.yml
          echo "datestamp: ${{ env.datestamp }}" >> topographia.info.yml

      - name: Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add topographia.info.yml
          git commit -m "Update version"
          git push origin HEAD:$GITHUB_REF

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
